"""Domain models for code actions, security findings, reviews, and PRs."""

from typing import Literal

from pydantic import BaseModel, Field


class FileAction(BaseModel):
    """A discrete file operation."""
    path: str = Field(description="Relative path inside workspace")
    action: Literal["CREATE", "MODIFY", "DELETE"]
    content: str = Field(description="Full file content or patch")
    description: str = Field(default="")
    sha256: str | None = None


class CodePlan(BaseModel):
    """Collection of file changes generated by Coding or Debug Agent."""
    summary: str
    actions: list[FileAction] = Field(default_factory=list)


class SecurityFinding(BaseModel):
    """Vulnerability identified during static code review."""
    severity: Literal["CRITICAL", "HIGH", "MEDIUM", "LOW"]
    category: str  # e.g., SQL_INJECTION, HARDCODED_SECRET, CSRF_DISABLED
    file: str
    line: int | None = None
    description: str
    remediation: str


class SecurityResult(BaseModel):
    """Consolidated security analysis result."""
    passed: bool
    has_critical: bool
    findings: list[SecurityFinding] = Field(default_factory=list)


class ReviewChecklistItem(BaseModel):
    """Individual verification check in code review."""
    name: str
    passed: bool
    details: str


class ReviewResult(BaseModel):
    """Contract-driven code review verdict."""
    verdict: Literal["APPROVED", "CHANGES_REQUESTED", "REJECTED"]
    score: float = Field(ge=0.0, le=1.0, description="Overall compliance score")
    summary: str
    checklist: list[ReviewChecklistItem] = Field(default_factory=list)
    required_changes: list[str] = Field(default_factory=list)


class PullRequestPayload(BaseModel):
    """Delivery payload for version control PR."""
    title: str
    branch: str
    base_branch: str
    body: str
    labels: list[str] = Field(default_factory=list)
    draft: bool = False
    pr_url: str | None = None
